service: meocon

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: development
  region: ap-southeast-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  echo:
    handler: bin/echo
    events:
      - http:
          path: echo
          method: post

  hello:
    handler: bin/hello_page
    events:
      - http:
          path: hello
          method: get